version: 2.1

jobs:
  build:
    docker:
      - image: afreeorange/build:latest
    steps:
      - checkout
      - run:
          name: Building package
          command: |
            git config user.email "auto@nikhil.io"
            git config user.name "CircleCI Builder"
            make build
      - persist_to_workspace:
          root: ./
          paths: ./*

  github-release:
    docker:
      - image: afreeorange/build:latest
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Releasing to GitHub
          command: /bin/bash ./.circleci/release

  aws-deploy:
    docker:
      - image: afreeorange/build:latest
    steps:
      - add_ssh_keys
      - run:
          name: Deploying to AWS
          command: ssh -o StrictHostKeyChecking=no $AWS_USER@$AWS_HOST -p $AWS_PORT $AWS_DEPLOY_SCRIPT

workflows:
  version: 2.1

  build-and-release:
    jobs:
      - build
      - github-release:
          requires:
            - build
      - aws-deploy:
          requires:
            - github-release
